
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador_Lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NUMERO = 2;
  public static final int LLAVI = 49;
  public static final int PARACADA = 19;
  public static final int LLAVF = 50;
  public static final int MULT = 31;
  public static final int CONJ = 37;
  public static final int ABRIR = 12;
  public static final int SI = 7;
  public static final int FUNCION = 6;
  public static final int RESTA = 30;
  public static final int DESDE = 13;
  public static final int ENTONCES = 9;
  public static final int CORCHETEFIN = 42;
  public static final int TNUMERO = 21;
  public static final int DECREMENTAR = 17;
  public static final int CORCHETEINI = 41;
  public static final int INCREMENTAR = 16;
  public static final int PRINCIPAL = 20;
  public static final int IGUAL = 39;
  public static final int SINO = 8;
  public static final int TAB = 52;
  public static final int MIENTRAS = 14;
  public static final int DIGUAL = 40;
  public static final int ESCRIBIR = 11;
  public static final int DIV = 32;
  public static final int PARFIN = 48;
  public static final int SUMA = 29;
  public static final int DISY = 36;
  public static final int ITERAR = 18;
  public static final int ID = 3;
  public static final int PARINI = 47;
  public static final int EOF = 0;
  public static final int CLASE = 5;
  public static final int error = 1;
  public static final int COMA = 45;
  public static final int NULO = 24;
  public static final int CADENA = 22;
  public static final int MODULO = 38;
  public static final int MENOR = 35;
  public static final int PCOMA = 44;
  public static final int EN = 27;
  public static final int MAYOR = 34;
  public static final int POTENCIA = 33;
  public static final int PUNTO = 46;
  public static final int INCLUIR = 4;
  public static final int FALSO = 26;
  public static final int DOSP = 43;
  public static final int HACER = 15;
  public static final int BOOLEANO = 23;
  public static final int RETORNAR = 10;
  public static final int VERDADERO = 25;
  public static final int TEXTO = 51;
  public static final int TARCHIVO = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "ID",
  "INCLUIR",
  "CLASE",
  "FUNCION",
  "SI",
  "SINO",
  "ENTONCES",
  "RETORNAR",
  "ESCRIBIR",
  "ABRIR",
  "DESDE",
  "MIENTRAS",
  "HACER",
  "INCREMENTAR",
  "DECREMENTAR",
  "ITERAR",
  "PARACADA",
  "PRINCIPAL",
  "TNUMERO",
  "CADENA",
  "BOOLEANO",
  "NULO",
  "VERDADERO",
  "FALSO",
  "EN",
  "TARCHIVO",
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "POTENCIA",
  "MAYOR",
  "MENOR",
  "DISY",
  "CONJ",
  "MODULO",
  "IGUAL",
  "DIGUAL",
  "CORCHETEINI",
  "CORCHETEFIN",
  "DOSP",
  "PCOMA",
  "COMA",
  "PUNTO",
  "PARINI",
  "PARFIN",
  "LLAVI",
  "LLAVF",
  "TEXTO",
  "TAB"
  };
}

