
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizador_Lexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
<<<<<<< HEAD
  public static final int NUMERO = 3;
  public static final int ELIMINAR = 23;
  public static final int PROPIED = 47;
  public static final int MULT = 31;
  public static final int CONST = 51;
  public static final int CHAR = 49;
  public static final int DEVOLVER = 2;
  public static final int CONJ = 27;
  public static final int SI = 7;
  public static final int FUNCION = 6;
  public static final int RESTA = 30;
  public static final int DESDE = 12;
  public static final int ENTONCES = 9;
  public static final int CORCHETEFIN = 39;
  public static final int COMENT = 46;
  public static final int CORCHETEINI = 38;
  public static final int INCREMENTAR = 15;
  public static final int PRINCIPAL = 17;
  public static final int IGUAL = 37;
  public static final int SINO = 8;
  public static final int MIENTRAS = 13;
  public static final int EXTIENDE = 24;
  public static final int TAB = 4;
  public static final int ESCRIBIR = 10;
  public static final int DIV = 32;
  public static final int PARFIN = 45;
  public static final int SUMA = 29;
  public static final int DISY = 26;
  public static final int ITERAR = 16;
  public static final int ID = 28;
  public static final int METD = 48;
  public static final int PARINI = 44;
  public static final int EOF = 0;
  public static final int ESTATICO = 25;
  public static final int CLASE = 5;
  public static final int error = 1;
  public static final int COMA = 42;
  public static final int NULO = 20;
  public static final int CADENA = 18;
  public static final int MODULO = 36;
  public static final int MENOR = 34;
  public static final int PCOMA = 41;
  public static final int MAYOR = 35;
  public static final int ENT = 50;
  public static final int POTENCIA = 33;
  public static final int PUNTO = 43;
  public static final int FALSO = 22;
  public static final int LEER = 11;
  public static final int DOSP = 40;
  public static final int HACER = 14;
  public static final int BOOLEANO = 19;
  public static final int VERDADERO = 21;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "DEVOLVER",
  "NUMERO",
  "TAB",
=======
  public static final int NUMERO = 2;
  public static final int LLAVI = 49;
  public static final int PARACADA = 19;
  public static final int LLAVF = 50;
  public static final int MULT = 31;
  public static final int CONJ = 37;
  public static final int ABRIR = 12;
  public static final int SI = 7;
  public static final int FUNCION = 6;
  public static final int RESTA = 30;
  public static final int DESDE = 13;
  public static final int ENTONCES = 9;
  public static final int CORCHETEFIN = 42;
  public static final int TNUMERO = 21;
  public static final int DECREMENTAR = 17;
  public static final int CORCHETEINI = 41;
  public static final int INCREMENTAR = 16;
  public static final int PRINCIPAL = 20;
  public static final int IGUAL = 39;
  public static final int SINO = 8;
  public static final int TAB = 52;
  public static final int MIENTRAS = 14;
  public static final int DIGUAL = 40;
  public static final int ESCRIBIR = 11;
  public static final int DIV = 32;
  public static final int PARFIN = 48;
  public static final int SUMA = 29;
  public static final int DISY = 36;
  public static final int ITERAR = 18;
  public static final int ID = 3;
  public static final int PARINI = 47;
  public static final int EOF = 0;
  public static final int CLASE = 5;
  public static final int error = 1;
  public static final int COMA = 45;
  public static final int NULO = 24;
  public static final int CADENA = 22;
  public static final int MODULO = 38;
  public static final int MENOR = 35;
  public static final int PCOMA = 44;
  public static final int EN = 27;
  public static final int MAYOR = 34;
  public static final int POTENCIA = 33;
  public static final int PUNTO = 46;
  public static final int INCLUIR = 4;
  public static final int FALSO = 26;
  public static final int DOSP = 43;
  public static final int HACER = 15;
  public static final int BOOLEANO = 23;
  public static final int RETORNAR = 10;
  public static final int VERDADERO = 25;
  public static final int TEXTO = 51;
  public static final int TARCHIVO = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMERO",
  "ID",
  "INCLUIR",
>>>>>>> oslo
  "CLASE",
  "FUNCION",
  "SI",
  "SINO",
  "ENTONCES",
<<<<<<< HEAD
  "ESCRIBIR",
  "LEER",
=======
  "RETORNAR",
  "ESCRIBIR",
  "ABRIR",
>>>>>>> oslo
  "DESDE",
  "MIENTRAS",
  "HACER",
  "INCREMENTAR",
<<<<<<< HEAD
  "ITERAR",
  "PRINCIPAL",
=======
  "DECREMENTAR",
  "ITERAR",
  "PARACADA",
  "PRINCIPAL",
  "TNUMERO",
>>>>>>> oslo
  "CADENA",
  "BOOLEANO",
  "NULO",
  "VERDADERO",
  "FALSO",
<<<<<<< HEAD
  "ELIMINAR",
  "EXTIENDE",
  "ESTATICO",
  "DISY",
  "CONJ",
  "ID",
=======
  "EN",
  "TARCHIVO",
>>>>>>> oslo
  "SUMA",
  "RESTA",
  "MULT",
  "DIV",
  "POTENCIA",
<<<<<<< HEAD
  "MENOR",
  "MAYOR",
  "MODULO",
  "IGUAL",
=======
  "MAYOR",
  "MENOR",
  "DISY",
  "CONJ",
  "MODULO",
  "IGUAL",
  "DIGUAL",
>>>>>>> oslo
  "CORCHETEINI",
  "CORCHETEFIN",
  "DOSP",
  "PCOMA",
  "COMA",
  "PUNTO",
  "PARINI",
  "PARFIN",
<<<<<<< HEAD
  "COMENT",
  "PROPIED",
  "METD",
  "CHAR",
  "ENT",
  "CONST"
=======
  "LLAVI",
  "LLAVF",
  "TEXTO",
  "TAB"
>>>>>>> oslo
  };
}

